import { readFileSync, writeFileSync } from 'node:fs';

// Writes src/generated/msw.ts: one MSW handler per operation in apps/api/openapi.json, each
// answering with its success status and an example body built from the response schema.

const SPEC_FILE = new URL('../../../apps/api/openapi.json', import.meta.url);
const OUTPUT_FILE = new URL('../src/generated/msw.ts', import.meta.url);
const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'patch'] as const;
const SUCCESS = /^2\d\d$/;
const MAX_DEPTH = 12;

interface JsonSchema {
  readonly $ref?: string;
  readonly type?: string | readonly string[];
  readonly enum?: readonly unknown[];
  readonly const?: unknown;
  readonly example?: unknown;
  readonly default?: unknown;
  readonly properties?: Readonly<Record<string, JsonSchema>>;
  readonly required?: readonly string[];
  readonly items?: JsonSchema;
  readonly prefixItems?: readonly JsonSchema[];
  readonly anyOf?: readonly JsonSchema[];
  readonly oneOf?: readonly JsonSchema[];
  readonly allOf?: readonly JsonSchema[];
  readonly minimum?: number;
  readonly format?: string;
}

interface Operation {
  readonly operationId?: string;
  readonly responses?: Readonly<
    Record<string, { content?: { 'application/json'?: { schema?: JsonSchema } } }>
  >;
}

interface Spec {
  readonly paths: Readonly<Record<string, Readonly<Record<string, Operation>>>>;
  readonly components?: { readonly schemas?: Readonly<Record<string, JsonSchema>> };
}

const spec = JSON.parse(readFileSync(SPEC_FILE, 'utf8')) as Spec;

function resolve(schema: JsonSchema): JsonSchema {
  const name = schema.$ref?.replace('#/components/schemas/', '');
  return name === undefined ? schema : (spec.components?.schemas?.[name] ?? {});
}

function scalarExample(schema: JsonSchema, type: string | undefined): unknown {
  if (type === 'string')
    return schema.format === 'date-time' ? '2026-09-25T12:00:00.000Z' : 'example';
  if (type === 'number' || type === 'integer') return schema.minimum ?? 1;
  if (type === 'boolean') return true;
  return null;
}

function objectExample(schema: JsonSchema, depth: number): Record<string, unknown> {
  const required = new Set(schema.required ?? []);
  return Object.fromEntries(
    Object.entries(schema.properties ?? {})
      .filter(([key]) => required.has(key))
      .map(([key, inner]) => [key, example(inner, depth + 1)]),
  );
}

function literalExample(schema: JsonSchema): unknown {
  return schema.example ?? schema.const ?? schema.enum?.[0];
}

function compositeExample(schema: JsonSchema, depth: number): unknown {
  if (schema.allOf !== undefined) {
    const parts = schema.allOf.map((part) => example(part, depth + 1));
    return parts.reduce<Record<string, unknown>>(
      (merged, part) => ({ ...merged, ...(part as Record<string, unknown>) }),
      {},
    );
  }
  const choice = schema.anyOf?.[0] ?? schema.oneOf?.[0];
  return choice === undefined ? undefined : example(choice, depth + 1);
}

function typedExample(schema: JsonSchema, depth: number): unknown {
  const types: readonly (string | undefined)[] =
    typeof schema.type === 'object' ? schema.type : [schema.type];
  const type = types.find((candidate) => candidate !== 'null');
  if (type === 'object') return objectExample(schema, depth);
  if (type === 'array') {
    const items = schema.prefixItems ?? (schema.items === undefined ? [] : [schema.items]);
    return items.map((item) => example(item, depth + 1));
  }
  return scalarExample(schema, type);
}

function example(raw: JsonSchema, depth = 0): unknown {
  const schema = resolve(raw);
  if (depth > MAX_DEPTH) return null;
  return literalExample(schema) ?? compositeExample(schema, depth) ?? typedExample(schema, depth);
}

function handlerSource(path: string, method: string, operation: Operation): string {
  const [status = '200', response] =
    Object.entries(operation.responses ?? {}).find(([code]) => SUCCESS.test(code)) ?? [];
  const schema = response?.content?.['application/json']?.schema;
  const mswPath = path.replace(/\{(\w+)\}/g, ':$1');
  const body =
    schema === undefined
      ? `new HttpResponse(null, { status: ${status} })`
      : `HttpResponse.json(${JSON.stringify(example(schema))}, { status: ${status} })`;
  return [
    `  // ${method.toUpperCase()} ${path}`,
    `  ${operation.operationId ?? `${method}${path}`}: http.${method}(\`\${baseUrl}${mswPath}\`, () =>`,
    `    ${body},`,
    '  ),',
  ].join('\n');
}

const handlers = Object.entries(spec.paths).flatMap(([path, item]) =>
  HTTP_METHODS.filter((method) => item[method] !== undefined).map((method) =>
    handlerSource(path, method, item[method] ?? {}),
  ),
);

const GENERATED_SOURCE = `/**
 * This file was generated by packages/api-client/scripts/generate-msw.ts from
 * apps/api/openapi.json. Do not edit it; run pnpm --filter @parkshape/api-client generate.
 */
import { http, HttpResponse, type HttpHandler } from 'msw';

/** One handler per API operation, keyed by operationId, answering with an example body. */
export function createApiHandlers(baseUrl: string): Record<string, HttpHandler> {
  return {
${handlers.join('\n')}
  };
}
`;

writeFileSync(OUTPUT_FILE, GENERATED_SOURCE);
process.stdout.write(`wrote ${OUTPUT_FILE.pathname} with ${String(handlers.length)} handlers\n`);
