import type { CatalogItemInput } from '../../schema/catalog.js';

export const facilityItems: readonly CatalogItemInput[] = [
  {
    id: 'path-light',
    category: 'lighting',
    name: 'Path light',
    geometryKind: 'point',
    // The plan follows the model, so it spans the arm as well as the pole base.
    footprint: { widthM: 0.22, depthM: 1.76 },
    heightM: 4,
    unitCost: { perItemCad: 6000 },
    surface: 'pervious',
    modelKey: 'path-light',
    scalePolicy: 'fixed',
  },
  {
    id: 'washroom-building',
    category: 'washroom',
    name: 'Washroom',
    geometryKind: 'point',
    footprint: { widthM: 8, depthM: 6.33 },
    heightM: 4,
    unitCost: { perItemCad: 900000 },
    surface: 'impervious',
    maxGrade: 0.02,
    modelKey: 'washroom-building',
    scalePolicy: 'fixed',
  },
  {
    id: 'drinking-fountain',
    category: 'amenity',
    name: 'Drinking fountain',
    geometryKind: 'point',
    footprint: { widthM: 0.8, depthM: 0.8 },
    heightM: 1,
    unitCost: { perItemCad: 35000 },
    surface: 'pervious',
    modelKey: 'drinking-fountain',
    scalePolicy: 'fixed',
  },
  {
    id: 'waste-bin',
    category: 'amenity',
    name: 'Waste bin',
    geometryKind: 'point',
    footprint: { widthM: 0.73, depthM: 0.73 },
    heightM: 1.1,
    unitCost: { perItemCad: 1500 },
    surface: 'pervious',
    modelKey: 'waste-bin',
    scalePolicy: 'fixed',
  },
  {
    id: 'bike-rack',
    category: 'amenity',
    name: 'Bike rack',
    geometryKind: 'point',
    footprint: { widthM: 2, depthM: 0.8 },
    heightM: 0.9,
    unitCost: { perItemCad: 1200 },
    surface: 'pervious',
    modelKey: 'bike-rack',
    scalePolicy: 'fixed',
  },
  {
    id: 'wayfinding-sign',
    category: 'amenity',
    name: 'Signpost',
    geometryKind: 'point',
    footprint: { widthM: 0.93, depthM: 0.19 },
    heightM: 2,
    unitCost: { perItemCad: 2500 },
    surface: 'pervious',
    modelKey: 'wayfinding-sign',
    scalePolicy: 'fixed',
  },
  {
    id: 'recycling-bin',
    category: 'amenity',
    name: 'Recycling bin',
    geometryKind: 'point',
    footprint: { widthM: 0.49, depthM: 0.55 },
    heightM: 1,
    unitCost: { perItemCad: 1500 },
    surface: 'pervious',
    modelKey: 'recycling-bin',
    scalePolicy: 'fixed',
  },
  {
    id: 'gazebo',
    category: 'amenity',
    name: 'Gazebo',
    geometryKind: 'point',
    // Filed as an amenity: a shelter category would need a schema change.
    footprint: { widthM: 3.11, depthM: 3.78 },
    heightM: 4.04,
    unitCost: { perItemCad: 60000 },
    surface: 'impervious',
    maxGrade: 0.05,
    modelKey: 'gazebo',
    scalePolicy: 'fixed',
  },
];
