import type { CatalogItemInput } from '../../schema/catalog.js';

/** Play surfaces under the structures are engineered wood fibre, so they count as pervious. */
export const playItems: readonly CatalogItemInput[] = [
  {
    id: 'playground-structure',
    category: 'play',
    name: 'Play structure',
    geometryKind: 'point',
    footprint: { widthM: 12, depthM: 10 },
    heightM: 4,
    unitCost: { perItemCad: 180000 },
    surface: 'pervious',
    maxGrade: 0.05,
    modelKey: 'playground-structure',
    scalePolicy: 'fixed',
  },
  {
    id: 'swings',
    category: 'play',
    name: 'Swing set',
    geometryKind: 'point',
    footprint: { widthM: 8, depthM: 4 },
    heightM: 2.6,
    unitCost: { perItemCad: 35000 },
    surface: 'pervious',
    maxGrade: 0.05,
    modelKey: 'swings',
    scalePolicy: 'fixed',
  },
  {
    id: 'spray-pad',
    category: 'play',
    name: 'Spray pad',
    geometryKind: 'point',
    footprint: { widthM: 10, depthM: 10 },
    heightM: 0.3,
    unitCost: { perItemCad: 250000 },
    surface: 'impervious',
    maxGrade: 0.02,
    modelKey: 'spray-pad',
    scalePolicy: 'fixed',
  },
  {
    id: 'outdoor-fitness-station',
    category: 'play',
    name: 'Fitness station',
    geometryKind: 'point',
    footprint: { widthM: 6, depthM: 4 },
    heightM: 2.5,
    unitCost: { perItemCad: 40000 },
    surface: 'pervious',
    maxGrade: 0.05,
    modelKey: 'outdoor-fitness-station',
    scalePolicy: 'fixed',
  },
];
