import type { CatalogItemInput } from '../../schema/catalog.js';

export const seatingItems: readonly CatalogItemInput[] = [
  {
    id: 'bench',
    category: 'seating',
    name: 'Bench',
    geometryKind: 'point',
    footprint: { widthM: 1.8, depthM: 1 },
    heightM: 0.9,
    unitCost: { perItemCad: 3500 },
    surface: 'pervious',
    modelKey: 'bench',
    scalePolicy: 'fixed',
  },
  {
    id: 'picnic-table',
    category: 'seating',
    name: 'Picnic table',
    geometryKind: 'point',
    footprint: { widthM: 1.8, depthM: 1.8 },
    heightM: 0.8,
    unitCost: { perItemCad: 4000 },
    surface: 'pervious',
    modelKey: 'picnic-table',
    scalePolicy: 'fixed',
  },
  {
    id: 'boulder-seat',
    category: 'seating',
    name: 'Boulder seat',
    geometryKind: 'point',
    footprint: { widthM: 1.73, depthM: 1.34 },
    heightM: 0.44,
    unitCost: { perItemCad: 2000 },
    surface: 'pervious',
    modelKey: 'boulder-seat',
    scalePolicy: 'fixed',
  },
  {
    id: 'log-seat',
    category: 'seating',
    name: 'Log seat',
    geometryKind: 'point',
    footprint: { widthM: 1.08, depthM: 0.59 },
    heightM: 0.45,
    unitCost: { perItemCad: 1500 },
    surface: 'pervious',
    modelKey: 'log-seat',
    scalePolicy: 'fixed',
  },
];
