import type { CatalogItemInput } from '../../schema/catalog.js';

export const surfaceItems: readonly CatalogItemInput[] = [
  {
    id: 'parking-lot-small',
    category: 'parking',
    name: 'Small parking lot',
    geometryKind: 'area',
    footprint: { minAreaM2: 150, defaultAreaM2: 400 },
    heightM: 0.1,
    unitCost: { perM2Cad: 150 },
    surface: 'impervious',
    maxGrade: 0.05,
    modelKey: 'parking-lot-small',
    scalePolicy: 'tile',
  },
  {
    id: 'lawn',
    category: 'ground',
    name: 'Lawn',
    geometryKind: 'area',
    footprint: { minAreaM2: 20, defaultAreaM2: 500 },
    heightM: 0.05,
    unitCost: { perM2Cad: 15 },
    surface: 'pervious',
    modelKey: 'lawn',
    scalePolicy: 'tile',
  },
  {
    id: 'meadow',
    category: 'ground',
    name: 'Meadow',
    geometryKind: 'area',
    footprint: { minAreaM2: 20, defaultAreaM2: 300 },
    heightM: 0.6,
    unitCost: { perM2Cad: 20 },
    surface: 'pervious',
    modelKey: 'meadow',
    scalePolicy: 'tile',
  },
  {
    id: 'plaza',
    category: 'plaza',
    name: 'Plaza',
    geometryKind: 'area',
    footprint: { minAreaM2: 30, defaultAreaM2: 200 },
    heightM: 0.1,
    unitCost: { perM2Cad: 300 },
    surface: 'impervious',
    maxGrade: 0.02,
    modelKey: 'plaza',
    scalePolicy: 'tile',
  },
];
