import type { CatalogItemInput } from '../../schema/catalog.js';

/** Native and common street trees, sized at maturity. Planted as 6 cm caliper stock. */
export const treeItems: readonly CatalogItemInput[] = [
  {
    id: 'bigleaf-maple',
    category: 'tree',
    name: 'Bigleaf maple',
    geometryKind: 'point',
    footprint: { widthM: 0.6, depthM: 0.6 },
    heightM: 25,
    crownRadiusMatureM: 9,
    matureDbhCm: 80,
    unitCost: { perItemCad: 1200 },
    surface: 'pervious',
    modelKey: 'tree-bigleaf-maple',
    scalePolicy: 'fixed',
  },
  {
    id: 'red-alder',
    category: 'tree',
    name: 'Red alder',
    geometryKind: 'point',
    footprint: { widthM: 0.6, depthM: 0.6 },
    heightM: 20,
    crownRadiusMatureM: 5,
    matureDbhCm: 40,
    unitCost: { perItemCad: 800 },
    surface: 'pervious',
    modelKey: 'tree-red-alder',
    scalePolicy: 'fixed',
  },
  {
    id: 'douglas-fir',
    category: 'tree',
    name: 'Douglas fir',
    geometryKind: 'point',
    footprint: { widthM: 0.6, depthM: 0.6 },
    heightM: 35,
    crownRadiusMatureM: 6,
    matureDbhCm: 90,
    unitCost: { perItemCad: 1100 },
    surface: 'pervious',
    modelKey: 'tree-douglas-fir',
    scalePolicy: 'fixed',
  },
  {
    id: 'western-red-cedar',
    category: 'tree',
    name: 'Western red cedar',
    geometryKind: 'point',
    footprint: { widthM: 0.6, depthM: 0.6 },
    heightM: 30,
    crownRadiusMatureM: 5.5,
    matureDbhCm: 90,
    unitCost: { perItemCad: 1100 },
    surface: 'pervious',
    modelKey: 'tree-western-red-cedar',
    scalePolicy: 'fixed',
  },
  {
    id: 'garry-oak',
    category: 'tree',
    name: 'Garry oak',
    geometryKind: 'point',
    footprint: { widthM: 0.6, depthM: 0.6 },
    heightM: 15,
    crownRadiusMatureM: 7,
    matureDbhCm: 60,
    unitCost: { perItemCad: 1500 },
    surface: 'pervious',
    modelKey: 'tree-garry-oak',
    scalePolicy: 'fixed',
  },
  {
    id: 'flowering-cherry',
    category: 'tree',
    name: 'Flowering cherry',
    geometryKind: 'point',
    footprint: { widthM: 0.6, depthM: 0.6 },
    heightM: 8,
    crownRadiusMatureM: 4,
    matureDbhCm: 45,
    unitCost: { perItemCad: 1000 },
    surface: 'pervious',
    modelKey: 'tree-flowering-cherry',
    scalePolicy: 'fixed',
  },
  {
    id: 'vine-maple',
    category: 'tree',
    name: 'Vine maple',
    geometryKind: 'point',
    footprint: { widthM: 0.6, depthM: 0.6 },
    heightM: 6,
    crownRadiusMatureM: 3,
    matureDbhCm: 10,
    unitCost: { perItemCad: 700 },
    surface: 'pervious',
    modelKey: 'tree-vine-maple',
    scalePolicy: 'fixed',
  },
];
