import { catalogItems, categorySchema } from '@parkshape/core';

import { SHORTCUTS } from '../editor/keyboard.js';

import type { EditorStrings } from './strings.js';

/** Plain strings for the component tests; the app passes its locale file instead. */
export const TEST_STRINGS: EditorStrings = {
  viewer: {
    canvasLabel: '3D editor',
    viewControls: 'View',
    resetView: 'Reset view',
    topDown: 'Top-down',
    birdsEye: "Bird's eye",
    compareWithToday: 'Compare with today',
    loadingMessage: 'Loading terrain',
  },
  catalog: Object.fromEntries(catalogItems.map((entry) => [entry.id, entry.name])),
  categories: Object.fromEntries(
    categorySchema.options.map((category) => [category, `Cat ${category}`]),
  ) as EditorStrings['categories'],
  palette: {
    heading: 'Add to the park',
    paint: 'Paint mode',
    paintHelp: 'Keep placing until Esc',
    terraformFold: 'Fold add',
    groups: {
      plants: 'Plants',
      paths: 'Paths',
      play: 'Play',
      seating: 'Seating',
      garden: 'Garden',
      amenities: 'Amenities',
    },
    costPerM2: '{cost}/m²',
    costPerModule: '{cost}/bed',
  },
  tools: {
    label: 'Tools',
    select: 'Select',
    path: 'Path',
    area: 'Area',
    terraform: 'Terraform',
    snap: 'Snap to grid',
    snapHelp: 'Hold Alt to turn off',
    itemsList: 'Items list',
    shortcuts: 'Shortcuts',
  },
  toolbar: {
    label: 'Selection',
    rotate: 'Rotate',
    duplicate: 'Duplicate',
    delete: 'Delete',
    locked: 'Locked',
  },
  reasons: {
    lockedFootprint: 'On {name}, which is locked',
    forbiddenZone: 'Inside {name}',
    tooSteep: 'Too steep for {name}',
    unknownItem: 'Unknown item',
    outsidePark: 'Outside the park',
  },
  notices: {
    locked: '{name} is locked',
    areaTooSmall: 'Needs {min} m2',
    pathTooShort: 'Needs 2 points',
    rejected: 'Nothing placed. {reason}.',
    pathHint: 'Click to add points',
    areaHint: 'Drag a rectangle',
    cornerHint: 'Click near an edge',
    placing: 'Placing {name}. Press Esc to stop.',
  },
  properties: {
    heading: 'Properties',
    many: '{count} selected',
    kind: 'Kind',
    cost: 'Cost',
    x: 'East (m)',
    y: 'North (m)',
    rotation: 'Rotation (degrees)',
    area: 'Area',
    areaValue: '{area} m²',
    areaSummary: '{area} m², {plots} plots',
    plots: 'Plots',
    length: 'Length',
    lengthValue: '{length} m',
    addCorner: 'Add corner',
  },
  itemsList: {
    heading: 'Items',
    empty: 'No items yet',
    position: '{x}, {y}',
    locked: 'Locked',
    nudge: 'Move {name}',
    north: 'North',
    south: 'South',
    east: 'East',
    west: 'West',
    delete: 'Delete {name}',
    rotate: 'Rotate {name}',
    duplicate: 'Duplicate {name}',
    addHeading: 'Add an item',
    addItem: 'Item',
    addX: 'East (m)',
    addY: 'North (m)',
    addButton: 'Add',
  },
  shortcuts: {
    heading: 'Keyboard shortcuts',
    close: 'Close',
    keyColumn: 'Key',
    actionColumn: 'Action',
    rows: Object.fromEntries(
      SHORTCUTS.map(({ action }) => [action, { keys: `key ${action}`, action: `do ${action}` }]),
    ) as EditorStrings['shortcuts']['rows'],
  },
  hints: {
    camera: 'Drag to turn, scroll to zoom',
    path: 'Click points, then press Enter',
    dismiss: 'Dismiss',
  },
  layers: {
    menu: 'Map layers',
    kinds: {
      street: 'Streets',
      sidewalk: 'Sidewalks',
      busStop: 'Bus stops',
      bikeway: 'Bike routes',
      parking: 'Parking',
    },
    legend: {
      street: 'Street',
      sidewalk: 'Sidewalk',
      busStop: 'Bus stop',
      bikeway: 'Bike route',
      parking: 'Parking',
    },
    failed: 'Street data did not load. Reload the page to try again.',
  },
  smallScreen: {
    heading: 'Use a bigger screen',
    body: 'The editor needs a desktop.',
    link: 'Vote instead',
  },
  terraform: {
    heading: 'Terraform',
    modeLabel: 'Brush',
    modes: {
      raise: 'Raise',
      lower: 'Lower',
      smooth: 'Smooth',
      flatten: 'Flatten',
      'level-item': 'Level under item',
    },
    radius: 'Radius (m)',
    strength: 'Strength',
    selectItemHint: 'Select an item to level under it',
    readoutHeading: 'Earthworks',
    cut: 'Cut: {value}',
    fill: 'Fill: {value}',
    net: 'Net: {value}',
    trucks: 'Haul: {value}',
    disturbed: 'Disturbed: {value}',
    hatchKey: 'Red hatching marks ground you cannot change.',
  },
};
